# Generated by Django 3.2.12 on 2024-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ashish', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('furniture_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('minimum_rental_days', models.IntegerField()),
            ],
        ),
    ]
